version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_dev
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: mydatabase

volumes:
  mongodb_data:
